blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/Roboroads/Streamline/discussions/new?category=ideas
    about: Have an idea for Streamline? Share it in our Discussions instead.
